"""
Code Generator - Generates C++ wrapper code for Android shared libraries.
"""

from pathlib import Path
from typing import List, Optional, Dict
from jinja2 import Environment, BaseLoader

from .symbol_extractor import LibraryInfo, Symbol


# Template for the main wrapper header
WRAPPER_HEADER_TEMPLATE = '''/**
 * Auto-generated wrapper for Android ARM64 shared libraries.
 * Generated by android-wrapper-generator.
 * 
 * DO NOT EDIT - This file is auto-generated.
 */

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <memory>

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle to the wrapper instance
typedef struct {{ wrapper_name }}_Handle* {{ wrapper_name }}Handle;

// Library management
{{ wrapper_name }}Handle {{ wrapper_name }}_Create(void);
void {{ wrapper_name }}_Destroy({{ wrapper_name }}Handle handle);
int {{ wrapper_name }}_Load({{ wrapper_name }}Handle handle, const char* lib_path);
int {{ wrapper_name }}_IsLoaded({{ wrapper_name }}Handle handle);

// Memory management (for structures with embedded pointers)
uint64_t {{ wrapper_name }}_AllocString({{ wrapper_name }}Handle handle, const char* str);
uint64_t {{ wrapper_name }}_AllocBuffer({{ wrapper_name }}Handle handle, const void* data, size_t size);
void {{ wrapper_name }}_ReadBuffer({{ wrapper_name }}Handle handle, uint64_t addr, void* data, size_t size);
void {{ wrapper_name }}_WriteBuffer({{ wrapper_name }}Handle handle, uint64_t addr, const void* data, size_t size);
void {{ wrapper_name }}_FreeMem({{ wrapper_name }}Handle handle, uint64_t addr);

{% for func in functions %}
// {{ func.library }}: {{ func.name }}
{{ func.return_type }} {{ wrapper_name }}_{{ func.name }}({{ wrapper_name }}Handle handle{{ func.param_list_with_types }});
{% endfor %}

#ifdef __cplusplus
}
#endif
'''

# Template for the wrapper implementation
WRAPPER_IMPL_TEMPLATE = '''/**
 * Auto-generated wrapper implementation for Android ARM64 shared libraries.
 * Generated by android-wrapper-generator.
 * 
 * DO NOT EDIT - This file is auto-generated.
 */

#include "{{ header_name }}"
#include <cross_shim/cross_shim.h>
#include <cross_shim/memory_manager.h>
#include <stdexcept>
#include <iostream>
#include <cstring>

// Embedded library data
{% for lib in libraries %}
// {{ lib.name }} - {{ lib.size }} bytes
static const unsigned char {{ lib.var_name }}_data[] = {
    #include "{{ lib.data_file }}"
};
static const size_t {{ lib.var_name }}_size = sizeof({{ lib.var_name }}_data);
{% endfor %}

// Internal wrapper class
class {{ wrapper_name }}Impl {
public:
    {{ wrapper_name }}Impl() : loaded_(false) {}
    ~{{ wrapper_name }}Impl() { unload(); }

    bool load(const std::string& lib_path) {
        if (loaded_) return true;

        try {
            std::cout << "[{{ wrapper_name }}] Starting library loading..." << std::endl;
            std::cout << "[{{ wrapper_name }}] Emulator initialized" << std::endl;
{% for lib in libraries %}
            // Load {{ lib.name }}
            std::cout << "[{{ wrapper_name }}] Loading {{ lib.name }} (" << {{ lib.var_name }}_size << " bytes)..." << std::endl;
            std::vector<uint8_t> {{ lib.var_name }}_vec(
                {{ lib.var_name }}_data,
                {{ lib.var_name }}_data + {{ lib.var_name }}_size
            );
            if (!emu_.load_library("{{ lib.name }}", {{ lib.var_name }}_vec)) {
                std::cerr << "[{{ wrapper_name }}] ERROR: Failed to load {{ lib.name }}" << std::endl;
                return false;
            }
            std::cout << "[{{ wrapper_name }}] {{ lib.name }} loaded successfully" << std::endl;
{% endfor %}

            // Hook HLE functions at their actual addresses in loaded libraries
            // This is needed for functions defined internally (not imported through GOT/PLT)
            std::cout << "[{{ wrapper_name }}] Hooking HLE functions at actual addresses..." << std::endl;
            emu_.hook_hle_functions_at_addresses();

            // Call init functions
            std::cout << "[{{ wrapper_name }}] Calling library init functions..." << std::endl;
            emu_.call_init_functions();
            std::cout << "[{{ wrapper_name }}] Init functions completed" << std::endl;
            loaded_ = true;
            return true;
        } catch (const std::exception& e) {
            std::cerr << "Exception loading libraries: " << e.what() << std::endl;
            return false;
        }
    }

    void unload() {
        loaded_ = false;
    }

    bool is_loaded() const { return loaded_; }
    cross_shim::Emulator& emulator() { return emu_; }

    uint64_t get_symbol(const std::string& name) {
        return emu_.get_symbol(name);
    }

    // Allocate a string in emulated memory and return its address
    uint64_t alloc_string(const char* str) {
        if (!str) return 0;
        size_t len = strlen(str) + 1;
        uint64_t addr = emu_.memory().heap().allocate(len, 8);
        if (addr) {
            emu_.mem_write(addr, str, len);
        }
        return addr;
    }

    // Allocate a buffer in emulated memory, optionally copying data from host
    uint64_t alloc_buffer(const void* data, size_t size) {
        // Sanity check: don't allocate more than 64MB
        if (size > 64 * 1024 * 1024) {
            std::cerr << "[WRAPPER] alloc_buffer: size too large: " << size << std::endl;
            return 0;
        }
        uint64_t addr = emu_.memory().heap().allocate(size, 8);
        if (addr && data) {
            emu_.mem_write(addr, data, size);
        }
        return addr;
    }

    // Read data from emulated memory back to host
    void read_buffer(uint64_t addr, void* data, size_t size) {
        if (addr && data) {
            emu_.mem_read(addr, data, size);
        }
    }

    // Free memory allocated in emulated space
    void free_mem(uint64_t addr) {
        if (addr) {
            emu_.memory().heap().free(addr);
        }
    }

private:
    cross_shim::Emulator emu_;
    bool loaded_;
};

// C API implementation
extern "C" {

{{ wrapper_name }}Handle {{ wrapper_name }}_Create(void) {
    return reinterpret_cast<{{ wrapper_name }}Handle>(new {{ wrapper_name }}Impl());
}

void {{ wrapper_name }}_Destroy({{ wrapper_name }}Handle handle) {
    delete reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
}

int {{ wrapper_name }}_Load({{ wrapper_name }}Handle handle, const char* lib_path) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    return impl->load(lib_path ? lib_path : ".") ? 1 : 0;
}

int {{ wrapper_name }}_IsLoaded({{ wrapper_name }}Handle handle) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    return impl->is_loaded() ? 1 : 0;
}

uint64_t {{ wrapper_name }}_AllocString({{ wrapper_name }}Handle handle, const char* str) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    return impl->alloc_string(str);
}

uint64_t {{ wrapper_name }}_AllocBuffer({{ wrapper_name }}Handle handle, const void* data, size_t size) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    return impl->alloc_buffer(data, size);
}

void {{ wrapper_name }}_ReadBuffer({{ wrapper_name }}Handle handle, uint64_t addr, void* data, size_t size) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    impl->read_buffer(addr, data, size);
}

void {{ wrapper_name }}_WriteBuffer({{ wrapper_name }}Handle handle, uint64_t addr, const void* data, size_t size) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    if (addr && data) {
        impl->emulator().mem_write(addr, data, size);
    }
}

void {{ wrapper_name }}_FreeMem({{ wrapper_name }}Handle handle, uint64_t addr) {
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    impl->free_mem(addr);
}

{% for func in functions %}
{{ func.return_type }} {{ wrapper_name }}_{{ func.name }}({{ wrapper_name }}Handle handle{{ func.param_list_with_types }}) {
{% if func.custom_impl %}
{{ func.custom_impl }}
{% else %}
    auto* impl = reinterpret_cast<{{ wrapper_name }}Impl*>(handle);
    uint64_t func_addr = impl->get_symbol("{{ func.name }}");
    if (func_addr == 0) {
        {% if func.return_type != 'void' %}return {{ func.default_return }};{% else %}return;{% endif %}
    }

{% for alloc in func.string_allocs %}
    {{ alloc }}
{% endfor %}
    std::vector<uint64_t> args = { {{ func.arg_list_with_strings }} };
    {% if func.return_type != 'void' %}
    uint64_t result = impl->emulator().call_function_direct(func_addr, args);
{% for free in func.string_frees %}
    {{ free }}
{% endfor %}
    return {{ func.return_cast }}result;
    {% else %}
    impl->emulator().call_function_direct(func_addr, args);
{% for free in func.string_frees %}
    {{ free }}
{% endfor %}
    {% endif %}
{% endif %}
}

{% endfor %}

} // extern "C"
'''

# Template for CMakeLists.txt
CMAKE_TEMPLATE = '''cmake_minimum_required(VERSION 3.20)
project({{ wrapper_name }} VERSION 1.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

# Find OpenSSL (required by CrossShim)
find_package(OpenSSL REQUIRED)

# Find CrossShim
find_package(CrossShim REQUIRED)

# Wrapper library sources
add_library({{ wrapper_name }} SHARED
    src/{{ wrapper_name }}.cpp
)

target_include_directories({{ wrapper_name }} PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
)

target_include_directories({{ wrapper_name }} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/data
)

target_link_libraries({{ wrapper_name }} PRIVATE
    CrossShim::cross_shim
)

# Installation
include(GNUInstallDirs)
install(TARGETS {{ wrapper_name }}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
install(FILES include/{{ wrapper_name }}.h
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
'''


class FunctionInfo:
    """Information about a function to wrap."""

    def __init__(self, symbol: Symbol, param_count: int = 0):
        self.name = symbol.name
        self.library = symbol.library
        self.address = symbol.address
        self.param_count = param_count
        # Default to generic types - can be overridden with type hints
        self.return_type = "uint64_t"
        self.param_types: List[str] = ["uint64_t"] * param_count
        self.param_names: List[str] = [f"arg{i}" for i in range(param_count)]
        # Custom implementation (if provided, replaces the generated implementation)
        self.custom_impl: Optional[str] = None

    def _is_string_type(self, type_str: str) -> bool:
        """Check if a type is a string (const char* or char*)."""
        return "char*" in type_str or "char *" in type_str

    def _is_output_ptr_type(self, type_str: str) -> bool:
        """Check if a type is an output pointer (e.g., 'out:uint32_t*')."""
        return type_str.startswith("out:")

    def _get_output_ptr_base_type(self, type_str: str) -> str:
        """Get the base type from an output pointer type."""
        # "out:uint32_t*" -> "uint32_t"
        base = type_str[4:]  # Remove "out:"
        if base.endswith("*"):
            base = base[:-1]
        return base

    def _get_output_ptr_size(self, type_str: str) -> str:
        """Get the size expression for an output pointer type."""
        base = self._get_output_ptr_base_type(type_str)
        return f"sizeof({base})"

    def _is_buffer_type(self, type_str: str) -> bool:
        """Check if a type is a buffer pointer (e.g., 'buffer:64' for 64-byte buffer)."""
        return type_str.startswith("buffer:")

    def _is_buffer_len_type(self, type_str: str) -> bool:
        """Check if a type is a buffer with length from another param (e.g., 'buffer_len:3' uses arg3 as length)."""
        return type_str.startswith("buffer_len:")

    def _get_buffer_size(self, type_str: str) -> str:
        """Get the size from a buffer type."""
        # "buffer:64" -> "64"
        return type_str[7:]

    def _get_buffer_len_param_index(self, type_str: str) -> int:
        """Get the parameter index that contains the length for a buffer_len type."""
        # "buffer_len:3" -> 3
        return int(type_str[11:])

    def _get_host_param_type(self, type_str: str) -> str:
        """Get the host-side parameter type for a given type hint."""
        if self._is_output_ptr_type(type_str):
            # "out:uint32_t*" -> "uint32_t*"
            return type_str[4:]
        elif self._is_buffer_type(type_str):
            # "buffer:64" -> "void*" (output buffer, gets read back)
            return "void*"
        elif self._is_buffer_len_type(type_str):
            # "buffer_len:3" -> "const void*" (input-only buffer)
            return "const void*"
        return type_str

    @property
    def param_list_with_types(self) -> str:
        """Get parameter list with types for function declaration."""
        if not self.param_types:
            return ""
        params = [f"{self._get_host_param_type(t)} {n}" for t, n in zip(self.param_types, self.param_names)]
        return ", " + ", ".join(params)

    @property
    def arg_list(self) -> str:
        """Get argument list for function call (deprecated, use arg_list_with_strings)."""
        if not self.param_names:
            return ""
        # Cast all args to uint64_t for emulator call
        return ", ".join([f"(uint64_t){n}" for n in self.param_names])

    @property
    def arg_list_with_strings(self) -> str:
        """Get argument list for function call, using allocated addresses for strings/buffers."""
        if not self.param_names:
            return ""
        args = []
        for i, (ptype, pname) in enumerate(zip(self.param_types, self.param_names)):
            if self._is_string_type(ptype):
                args.append(f"{pname}_addr")
            elif self._is_output_ptr_type(ptype) or self._is_buffer_type(ptype) or self._is_buffer_len_type(ptype):
                args.append(f"{pname}_addr")
            else:
                args.append(f"(uint64_t){pname}")
        return ", ".join(args)

    @property
    def string_allocs(self) -> List[str]:
        """Get list of allocation statements for strings, output pointers, and buffers."""
        allocs = []
        for i, (ptype, pname) in enumerate(zip(self.param_types, self.param_names)):
            if self._is_string_type(ptype):
                allocs.append(f"uint64_t {pname}_addr = impl->alloc_string({pname});")
            elif self._is_output_ptr_type(ptype):
                base_type = self._get_output_ptr_base_type(ptype)
                size = self._get_output_ptr_size(ptype)
                allocs.append(f"uint64_t {pname}_addr = impl->alloc_buffer({pname}, {size});")
            elif self._is_buffer_type(ptype):
                size = self._get_buffer_size(ptype)
                allocs.append(f"uint64_t {pname}_addr = impl->alloc_buffer({pname}, {size});")
            elif self._is_buffer_len_type(ptype):
                # Use another parameter as the length
                len_param_idx = self._get_buffer_len_param_index(ptype)
                len_param_name = self.param_names[len_param_idx]
                allocs.append(f"uint64_t {pname}_addr = impl->alloc_buffer({pname}, {len_param_name});")
        return allocs

    @property
    def string_frees(self) -> List[str]:
        """Get list of free statements and read-backs for output pointers."""
        frees = []
        # First, read back output pointers (not buffer_len since those are input-only)
        for i, (ptype, pname) in enumerate(zip(self.param_types, self.param_names)):
            if self._is_output_ptr_type(ptype):
                size = self._get_output_ptr_size(ptype)
                frees.append(f"if ({pname}) impl->read_buffer({pname}_addr, {pname}, {size});")
            elif self._is_buffer_type(ptype):
                size = self._get_buffer_size(ptype)
                frees.append(f"if ({pname}) impl->read_buffer({pname}_addr, {pname}, {size});")
            # Note: buffer_len types are input-only, no read-back needed
        # Then free all allocated memory
        for i, (ptype, pname) in enumerate(zip(self.param_types, self.param_names)):
            if self._is_string_type(ptype):
                frees.append(f"impl->free_mem({pname}_addr);")
            elif self._is_output_ptr_type(ptype) or self._is_buffer_type(ptype) or self._is_buffer_len_type(ptype):
                frees.append(f"impl->free_mem({pname}_addr);")
        return frees

    @property
    def default_return(self) -> str:
        """Get default return value for error cases."""
        if self.return_type == "void":
            return ""
        elif self.return_type in ("int", "int32_t", "int64_t"):
            return "-1"
        elif self.return_type in ("uint32_t", "uint64_t", "size_t"):
            return "0"
        elif "*" in self.return_type:
            return "nullptr"
        else:
            return "0"

    @property
    def return_cast(self) -> str:
        """Get cast for return value."""
        if self.return_type == "uint64_t":
            return ""
        return f"({self.return_type})"


class CodeGenerator:
    """
    Generates C++ wrapper code for Android shared libraries.

    Takes library information from SymbolExtractor and generates:
    - Header file with C API declarations
    - Implementation file with wrapper code
    - CMakeLists.txt for building
    - Embedded library data files
    """

    def __init__(self, wrapper_name: str):
        """
        Initialize the code generator.

        Args:
            wrapper_name: Name for the generated wrapper (e.g., "tutk_wrapper")
        """
        self.wrapper_name = wrapper_name
        self.env = Environment(loader=BaseLoader())
        self.libraries: List[LibraryInfo] = []
        self.functions: List[FunctionInfo] = []
        self.type_hints: Dict[str, Dict[str, str]] = {}  # func_name -> {return_type, param_types}

    def add_library(self, lib_info: LibraryInfo) -> None:
        """Add a library to be wrapped."""
        self.libraries.append(lib_info)

        # Track function names we've already added to avoid duplicates
        existing_names = {f.name for f in self.functions}

        # Add all exported functions (skip duplicates)
        for sym in lib_info.get_exported_functions():
            # Skip if we already have a function with this name
            if sym.name in existing_names:
                continue

            func = FunctionInfo(sym)
            # Apply type hints if available
            if sym.name in self.type_hints:
                hints = self.type_hints[sym.name]
                if "return_type" in hints:
                    func.return_type = hints["return_type"]
                if "param_types" in hints:
                    func.param_types = hints["param_types"]
                    func.param_names = [f"arg{i}" for i in range(len(func.param_types))]
                    func.param_count = len(func.param_types)
                if "custom_impl" in hints:
                    func.custom_impl = hints["custom_impl"]
            self.functions.append(func)
            existing_names.add(sym.name)

    def set_type_hints(self, hints: Dict[str, Dict[str, str]]) -> None:
        """
        Set type hints for functions.

        Args:
            hints: Dict mapping function names to type info:
                   {"func_name": {"return_type": "int", "param_types": ["int", "char*"]}}
        """
        self.type_hints = hints

    def generate(self, output_dir: str) -> None:
        """
        Generate all wrapper files.

        Args:
            output_dir: Directory to write generated files
        """
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        # Create subdirectories
        (out_path / "include").mkdir(exist_ok=True)
        (out_path / "src").mkdir(exist_ok=True)
        (out_path / "data").mkdir(exist_ok=True)

        # Generate embedded library data files
        lib_data = self._generate_library_data(out_path / "data")

        # Generate header
        self._generate_header(out_path / "include" / f"{self.wrapper_name}.h")

        # Generate implementation
        self._generate_impl(out_path / "src" / f"{self.wrapper_name}.cpp", lib_data)

        # Generate CMakeLists.txt
        self._generate_cmake(out_path / "CMakeLists.txt")

    def _generate_library_data(self, data_dir: Path) -> List[Dict]:
        """Generate embedded library data files."""
        lib_data = []

        for lib in self.libraries:
            var_name = lib.name.replace(".", "_").replace("-", "_")
            data_file = f"{var_name}.inc"

            # Read library binary data
            with open(lib.path, "rb") as f:
                data = f.read()

            # Write as C array include file
            with open(data_dir / data_file, "w") as f:
                for i, byte in enumerate(data):
                    if i > 0:
                        f.write(",")
                    if i % 16 == 0:
                        f.write("\n    ")
                    f.write(f"0x{byte:02x}")
                f.write("\n")

            lib_data.append({
                "name": lib.name,
                "var_name": var_name,
                "data_file": data_file,
                "size": len(data),
            })

        return lib_data

    def _generate_header(self, path: Path) -> None:
        """Generate the wrapper header file."""
        template = self.env.from_string(WRAPPER_HEADER_TEMPLATE)
        content = template.render(
            wrapper_name=self.wrapper_name,
            functions=self.functions,
        )
        path.write_text(content)

    def _generate_impl(self, path: Path, lib_data: List[Dict]) -> None:
        """Generate the wrapper implementation file."""
        template = self.env.from_string(WRAPPER_IMPL_TEMPLATE)
        content = template.render(
            wrapper_name=self.wrapper_name,
            header_name=f"{self.wrapper_name}.h",
            libraries=lib_data,
            functions=self.functions,
        )
        path.write_text(content)

    def _generate_cmake(self, path: Path) -> None:
        """Generate CMakeLists.txt."""
        template = self.env.from_string(CMAKE_TEMPLATE)
        content = template.render(wrapper_name=self.wrapper_name)
        path.write_text(content)

